export const mockData = {
  "configuracoes": {
    "NOME_EMPRESA": "GPV Associados",
    "TITULO_SISTEMA": "Organograma GPV",
    "SUBTITULO_SISTEMA": "Estrutura corporativa e equipes",
    "VERSAO": "0.2.0"
  },
  "colaboradores": [
    {
      "ID": "CORP-001",
      "NomeCompleto": "CEO e Sócios",
      "NomeExibicao": "CEO e Sócios",
      "Cargo": "Liderança Corporativa",
      "Setor": "Corporativo",
      "GestorID": "",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 0,
      "Tipo": "institucional"
    },
    {
      "ID": "COL-001",
      "NomeCompleto": "Daniel Silva",
      "NomeExibicao": "Daniel Silva",
      "Cargo": "Diretor Administrativo",
      "Setor": "Administrativo",
      "GestorID": "CORP-001",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-004.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 1,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-002",
      "NomeCompleto": "Gabriel Torres",
      "NomeExibicao": "Gabriel Torres",
      "Cargo": "Diretor Operacional",
      "Setor": "Operacional",
      "GestorID": "CORP-001",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-009.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 2,
      "Nivel": 1,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-003",
      "NomeCompleto": "Keyla",
      "NomeExibicao": "Keyla",
      "Cargo": "Diretora Financeira",
      "Setor": "Financeiro",
      "GestorID": "CORP-001",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-013.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 3,
      "Nivel": 1,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-004",
      "NomeCompleto": "Joice Gomes",
      "NomeExibicao": "Joice Gomes",
      "Cargo": "Gestora de RH",
      "Setor": "Recursos Humanos",
      "GestorID": "COL-001",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-012.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-005",
      "NomeCompleto": "Pedro",
      "NomeExibicao": "Pedro",
      "Cargo": "Analista de TI",
      "Setor": "Tecnologia",
      "GestorID": "COL-001",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-021.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 2,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-006",
      "NomeCompleto": "Luiza",
      "NomeExibicao": "Luiza",
      "Cargo": "Auxiliar de Marketing",
      "Setor": "Marketing",
      "GestorID": "COL-001",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-015.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 3,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-007",
      "NomeCompleto": "Gabriel",
      "NomeExibicao": "Gabriel",
      "Cargo": "Auxiliar de Marketing",
      "Setor": "Marketing",
      "GestorID": "COL-001",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-010.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 4,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-008",
      "NomeCompleto": "Renata Larissa",
      "NomeExibicao": "Renata Larissa",
      "Cargo": "Gestora de Assistência 24h",
      "Setor": "Assistência 24h",
      "GestorID": "COL-002",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-022.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-009",
      "NomeCompleto": "Lucas Soares",
      "NomeExibicao": "Lucas Soares",
      "Cargo": "Gestor de Eventos",
      "Setor": "Eventos",
      "GestorID": "COL-002",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-014.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 2,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-010",
      "NomeCompleto": "Anderson Tabosa",
      "NomeExibicao": "Anderson Tabosa",
      "Cargo": "Gestor de Rastreamento",
      "Setor": "Rastreamento",
      "GestorID": "COL-002",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-002.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 3,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-011",
      "NomeCompleto": "Nataly",
      "NomeExibicao": "Nataly",
      "Cargo": "Coordenadora de SDA",
      "Setor": "SDA",
      "GestorID": "COL-002",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-020.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 4,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-012",
      "NomeCompleto": "Fabiana",
      "NomeExibicao": "Fabiana",
      "Cargo": "Analista de SDC",
      "Setor": "SDC",
      "GestorID": "COL-002",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-008.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 5,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-013",
      "NomeCompleto": "Thainá",
      "NomeExibicao": "Thainá",
      "Cargo": "Coordenadora de Eventos",
      "Setor": "Eventos",
      "GestorID": "COL-009",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 3,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-014",
      "NomeCompleto": "Maria Eduarda",
      "NomeExibicao": "Maria Eduarda",
      "Cargo": "Coordenadora de Rastreamento",
      "Setor": "Rastreamento",
      "GestorID": "COL-010",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-016.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 3,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-015",
      "NomeCompleto": "Caio",
      "NomeExibicao": "Caio",
      "Cargo": "Auxiliar de SDC",
      "Setor": "SDC",
      "GestorID": "COL-012",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-003.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 3,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-016",
      "NomeCompleto": "Wanessa",
      "NomeExibicao": "Wanessa",
      "Cargo": "Auxiliar de SDC",
      "Setor": "SDC",
      "GestorID": "COL-012",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 2,
      "Nivel": 3,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-017",
      "NomeCompleto": "Jayne",
      "NomeExibicao": "Jayne",
      "Cargo": "Auxiliar de SDC",
      "Setor": "SDC",
      "GestorID": "COL-012",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 3,
      "Nivel": 3,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-018",
      "NomeCompleto": "Yarissa",
      "NomeExibicao": "Yarissa",
      "Cargo": "Auxiliar de Rastreamento",
      "Setor": "Rastreamento",
      "GestorID": "COL-014",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 4,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-019",
      "NomeCompleto": "David",
      "NomeExibicao": "David",
      "Cargo": "Auxiliar de Rastreamento",
      "Setor": "Rastreamento",
      "GestorID": "COL-014",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 2,
      "Nivel": 4,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-020",
      "NomeCompleto": "Moniely",
      "NomeExibicao": "Moniely",
      "Cargo": "Auxiliar de Rastreamento",
      "Setor": "Rastreamento",
      "GestorID": "COL-014",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-018.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 3,
      "Nivel": 4,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-021",
      "NomeCompleto": "Alice",
      "NomeExibicao": "Alice",
      "Cargo": "Auxiliar de Eventos",
      "Setor": "Eventos",
      "GestorID": "COL-013",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-001.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 4,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-022",
      "NomeCompleto": "Vitória",
      "NomeExibicao": "Vitória",
      "Cargo": "Auxiliar de Eventos",
      "Setor": "Eventos",
      "GestorID": "COL-013",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 2,
      "Nivel": 4,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-023",
      "NomeCompleto": "Danrley",
      "NomeExibicao": "Danrley",
      "Cargo": "Auxiliar de Eventos",
      "Setor": "Eventos",
      "GestorID": "COL-013",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-005.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 3,
      "Nivel": 4,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-024",
      "NomeCompleto": "Vandilson",
      "NomeExibicao": "Vandilson",
      "Cargo": "Regulador de Eventos",
      "Setor": "Eventos",
      "GestorID": "COL-013",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-024.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 4,
      "Nivel": 4,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-025",
      "NomeCompleto": "Mateus",
      "NomeExibicao": "Mateus",
      "Cargo": "Regulador de Eventos",
      "Setor": "Eventos",
      "GestorID": "COL-013",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-017.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 5,
      "Nivel": 4,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-026",
      "NomeCompleto": "Emerson Eusébio",
      "NomeExibicao": "Emerson Eusébio",
      "Cargo": "Gestor Financeiro",
      "Setor": "Financeiro",
      "GestorID": "COL-003",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-007.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-027",
      "NomeCompleto": "Sarah",
      "NomeExibicao": "Sarah",
      "Cargo": "Coordenadora de Cobrança",
      "Setor": "Cobrança",
      "GestorID": "COL-003",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-023.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 2,
      "Nivel": 2,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-028",
      "NomeCompleto": "Nadja Nataline",
      "NomeExibicao": "Nadja Nataline",
      "Cargo": "Auxiliar Financeira",
      "Setor": "Financeiro",
      "GestorID": "COL-026",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-019.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 3,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-029",
      "NomeCompleto": "Lucas",
      "NomeExibicao": "Lucas",
      "Cargo": "Auxiliar Financeiro",
      "Setor": "Financeiro",
      "GestorID": "COL-026",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 2,
      "Nivel": 3,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-030",
      "NomeCompleto": "Vitória Lais",
      "NomeExibicao": "Vitória Lais",
      "Cargo": "Auxiliar de Cobrança",
      "Setor": "Cobrança",
      "GestorID": "COL-027",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 1,
      "Nivel": 3,
      "Tipo": "colaborador"
    },
    {
      "ID": "COL-031",
      "NomeCompleto": "Eliane Silva",
      "NomeExibicao": "Eliane Silva",
      "Cargo": "Auxiliar de Cobrança",
      "Setor": "Cobrança",
      "GestorID": "COL-027",
      "DataNascimento": "",
      "DataAdmissao": "",
      "FotoURL": "/assets/colaboradores/COL-006.png",
      "Email": "",
      "Telefone": "",
      "Biografia": "",
      "Responsabilidades": "",
      "Unidade": "",
      "Status": "Ativo",
      "Ordem": 2,
      "Nivel": 3,
      "Tipo": "colaborador"
    }
  ],
  "resumo": {
    "totalColaboradores": 31,
    "totalSetores": 12,
    "totalLiderancas": 10
  }
};
